# Generated by Django 5.2.11 on 2026-02-05 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'area_conhecimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InteracaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_interacao', models.CharField(max_length=20)),
                ('peso', models.IntegerField()),
                ('data_interacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'interacao_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('editora', models.CharField(blank=True, max_length=255, null=True)),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('capa_url', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('ano_publicacao', models.IntegerField(blank=True, null=True)),
                ('data_cadastro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'livro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecomendacaoLivro',
            fields=[
                ('usuario_id', models.IntegerField()),
                ('livro_id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo_livro', models.CharField(max_length=255)),
                ('area_conhecimento', models.CharField(max_length=255)),
                ('score_final', models.IntegerField()),
            ],
            options={
                'db_table': 'vw_recomendacao_livros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('visitante', 'Visitante'), ('autenticado', 'Usuário autenticado'), ('admin', 'Administrador')], default='autenticado', max_length=30)),
                ('perfil_academico', models.CharField(max_length=100)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
