# Generated by Django 5.2.11 on 2026-02-07 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAreaInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(db_column='area_conhecimento_id', on_delete=django.db.models.deletion.CASCADE, to='core.areaconhecimento')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'db_table': 'usuario_area_interesse',
                'unique_together': {('usuario', 'area')},
            },
        ),
    ]
