# Generated by Django 5.2.11 on 2026-02-09 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuarioareainteresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalavraChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AreaPalavraChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.areaconhecimento')),
                ('palavra_chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.palavrachave')),
            ],
        ),
        migrations.CreateModel(
            name='LivroAreaConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.areaconhecimento')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.livro')),
            ],
            options={
                'db_table': 'livro_area_conhecimento',
                'unique_together': {('livro', 'area')},
            },
        ),
    ]
