# Generated by Django 5.2.11 on 2026-04-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_palavrachave_areapalavrachave_livroareaconhecimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areapalavrachave',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='livroareaconhecimento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='palavrachave',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuarioareainteresse',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='usuario',
            name='consentimento_recomendacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_consentimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='versao_termo_consentimento',
            field=models.CharField(default='1.0', max_length=20),
        ),
    ]
