# Generated by Django 5.2.11 on 2026-04-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_areapalavrachave_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivroPalavraChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'livro_palavra_chave',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='areapalavrachave',
            table='core_areapalavrachave',
        ),
        migrations.AlterModelTable(
            name='palavrachave',
            table='palavra_chave',
        ),
    ]
